FROM docker.io/postgres:17.1-alpine

# Create the shared data directory & volume inside the container. Like the pgdata directory,
# this directory will change ownership once the container runs.
RUN mkdir -p "/shared" && chown -R postgres:postgres "/shared" && chmod 1777 "/shared"
VOLUME /shared
